### ISSUE TITLE
fizyr/keras-retinanet2ncnn

### ISSUE THREAD

**Issue by zengwb-lx** [MarsTechHAN/keras2ncnn#31]
got KeyError: 'attr'
class UpsampleLike(keras.layers.Layer):
    """ Keras layer for upsampling a Tensor to be the same shape as another Tensor.
    """

    def call(self, inputs, **kwargs):
        source, target = inputs
        target_shape = keras.backend.shape(target)
        if keras.backend.image_data_format() == 'channels_first':
            source = backend.transpose(source, (0, 2, 3, 1))
            output = backend.resize_images(source, (target_shape[2], target_shape[3]), method='nearest')
            output = backend.transpose(output, (0, 3, 1, 2))
            return output
        else:
            return backend.resize_images(source, (target_shape[1], target_shape[2]), method='nearest')

this OP UpsampleLike is not support， Can you help me solve it,thanks!

**Comment by MarsTechHAN** [comment]
Keras will insert the custom layer as a custom object, and the converter are not able to parse it.
I think you need to flatten your model (using the sequential layer with custom layer inside instead of a custom layer) in order to use the converter. 

(or, you can try to implement this layer by your own, since it is just a nearest resize)

**Comment by zengwb-lx** [comment]
OK thanks！
